baseURL = 'https://jennifersmith.github.io/blog'
languageCode = 'en-au'
title = 'Fly Log'
theme = 'simpler'
[params]
FooterText = 'customised copy of [no-js-hugo-theme](https://github.com/stevenengler/no-js-hugo-theme/tree/master)'
